/**
 * PDF Export utility using browser print
 * Creates a printable HTML document and triggers print dialog
 */

/**
 * Generate HTML content for the interview guide
 * @param {Object} interviewData - The interview data object
 * @param {Object} repoData - Repository information
 * @returns {string} HTML string
 */
const generatePrintableHTML = (interviewData, repoData) => {
  const questionsHTML = interviewData.questions
    .map(
      (q, i) => `
      <div class="question">
        <div class="question-header">
          <span class="question-number">${i + 1}</span>
          <span class="category">${q.category}</span>
          <span class="difficulty ${q.difficulty.toLowerCase()}">${q.difficulty}</span>
        </div>
        <h3>${q.q}</h3>
        <div class="strategy">
          <strong>💡 Strategy:</strong>
          <p>${q.strategy}</p>
        </div>
        <div class="answer">
          <strong>✅ Model Answer:</strong>
          <p>${q.sample_answer}</p>
        </div>
      </div>
    `
    )
    .join('');

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <title>Interview Prep Guide - ${repoData.repo}</title>
      <style>
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body { 
          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
          line-height: 1.6;
          color: #1e293b;
          padding: 40px;
          max-width: 800px;
          margin: 0 auto;
        }
        .header {
          text-align: center;
          margin-bottom: 40px;
          padding-bottom: 20px;
          border-bottom: 2px solid #0891b2;
        }
        .header h1 { color: #0891b2; margin-bottom: 8px; }
        .header .repo { color: #64748b; font-size: 14px; }
        .section { margin-bottom: 30px; }
        .section h2 { 
          color: #0891b2; 
          font-size: 14px; 
          text-transform: uppercase; 
          letter-spacing: 1px;
          margin-bottom: 12px;
        }
        .tech-stack { display: flex; flex-wrap: wrap; gap: 8px; }
        .tech-stack span {
          background: #f1f5f9;
          padding: 4px 12px;
          border-radius: 4px;
          font-size: 13px;
        }
        .question {
          background: #f8fafc;
          border: 1px solid #e2e8f0;
          border-radius: 8px;
          padding: 20px;
          margin-bottom: 20px;
          page-break-inside: avoid;
        }
        .question-header {
          display: flex;
          align-items: center;
          gap: 10px;
          margin-bottom: 12px;
        }
        .question-number {
          background: #0891b2;
          color: white;
          width: 24px;
          height: 24px;
          border-radius: 50%;
          display: flex;
          align-items: center;
          justify-content: center;
          font-size: 12px;
          font-weight: bold;
        }
        .category {
          background: #e0f2fe;
          color: #0369a1;
          padding: 2px 8px;
          border-radius: 4px;
          font-size: 11px;
          font-weight: 600;
        }
        .difficulty {
          padding: 2px 8px;
          border-radius: 4px;
          font-size: 11px;
          font-weight: 600;
        }
        .difficulty.junior { background: #dcfce7; color: #166534; }
        .difficulty.mid { background: #fef9c3; color: #854d0e; }
        .difficulty.senior { background: #fee2e2; color: #991b1b; }
        .question h3 { font-size: 16px; margin-bottom: 16px; }
        .strategy, .answer { margin-top: 12px; }
        .strategy strong, .answer strong { 
          display: block; 
          font-size: 12px; 
          color: #64748b;
          margin-bottom: 4px;
        }
        .strategy p, .answer p { font-size: 14px; color: #475569; }
        .footer {
          margin-top: 40px;
          padding-top: 20px;
          border-top: 1px solid #e2e8f0;
          text-align: center;
          color: #94a3b8;
          font-size: 12px;
        }
        @media print {
          body { padding: 20px; }
          .question { break-inside: avoid; }
        }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>📋 Interview Prep Guide</h1>
        <p class="repo">${repoData.owner}/${repoData.repo}</p>
      </div>

      <div class="section">
        <h2>📝 Project Summary</h2>
        <p>${interviewData.project_summary}</p>
      </div>

      <div class="section">
        <h2>🛠️ Tech Stack</h2>
        <div class="tech-stack">
          ${interviewData.tech_stack.map((t) => `<span>${t}</span>`).join('')}
        </div>
      </div>

      <div class="section">
        <h2>❓ Interview Questions</h2>
        ${questionsHTML}
      </div>

      <div class="footer">
        Generated by Repo Interview Prepper • ${new Date().toLocaleDateString()}
      </div>
    </body>
    </html>
  `;
};

/**
 * Export interview guide as PDF using print dialog
 * @param {Object} interviewData - The interview data
 * @param {Object} repoData - Repository data
 */
export const exportToPdf = (interviewData, repoData) => {
  const html = generatePrintableHTML(interviewData, repoData);
  
  // Create a new window for printing
  const printWindow = window.open('', '_blank');
  if (!printWindow) {
    throw new Error('Please allow popups to export PDF');
  }
  
  printWindow.document.write(html);
  printWindow.document.close();
  
  // Wait for content to load, then print
  printWindow.onload = () => {
    printWindow.focus();
    printWindow.print();
  };
};

/**
 * Export as JSON file
 * @param {Object} interviewData - The interview data
 * @param {Object} repoData - Repository data
 */
export const exportToJson = (interviewData, repoData) => {
  const data = {
    repository: repoData,
    generatedAt: new Date().toISOString(),
    ...interviewData,
  };
  
  const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${repoData.repo}_interview_data.json`;
  a.click();
  URL.revokeObjectURL(url);
};

export default exportToPdf;
